### ISSUE TITLE
[Feature Request]: `scaffdog generate` accept template parameter

### ISSUE THREAD

**Issue by lidqqq** [cats-oss/scaffdog#224]
I was hoping if there is an option to accept template parameter with `scaffdog generate` in a specific case when we know what we should choose obviously.

## Expected Behavior

If we have templates like

```
npx scaffdog list
- hello
```

I hope

`npx scaffdog generate --template|-t hello`

then, we will skip the question choosing template about `? Please select a document. (Use arrow keys)`.

## Actual Behavior

none

## Steps to Reproduce (including precondition)

none, it's not a bug.

## Screenshot on This Problem (if possible)

none, it's not a bug.

## Your Environment

- OS: macOS latest
- scaffdog version: latest

**Comment by wadackel** [comment]
Hi @lidqqq, Thank you for using scaffdog :dog:

You can use `<name>` positional arguments. (sub-command signature: `scaffdog generate <name>`)
For example, use the following command:

```bash
$ scaffdog generate hello
# Skip the prompt choosing template select
```

I hope it helps.

**Comment by lidqqq** [comment]
@wadackel 
Oh, we can already do the same thing by that... 🤦‍♂️ 
Sorry to bother you, I'll read the document more carefully in the future. 😵‍💫 
https://github.com/cats-oss/scaffdog#:~:text=%24%20npx%20scaffdog%20generate%20hello
